### ISSUE TITLE
Duvida tabela decision.csv

### ISSUE THREAD

**Issue by rprata** [ajdavidl/corpus-atas-copom#1]
Gostaria de entender como funciona o campo decision na tabela. O exemplo abaixo tem uma mudança de 17.25 -> 16.75 -> 16 e todas as decisões são de raise. Não seria ao contrário?
<img width="308" alt="Screenshot 2024-11-14 at 09 13 48" src="https://github.com/user-attachments/assets/0ca9bcf0-bbc4-4b48-8df7-09230c47d953">

**Comment by ajdavidl** [comment]
A tabela apresenta as reuniões **da mais recente para a mais antiga**. 

O exemplo apresentado deve ser interpretado da seguinte forma: 
- na reunião 99, a taxa era de 16%;
- na reunião 100, a taxa subiu para 16,25%, logo a decisão "raise";
- na reunião 101, a taxa subiu para 16,75%, portanto "raise";
- na reunião 102, a taxa subiu para 17,25%, "raise" de novo.

Para evitar dúvidas futuras, vou ajustar a tabela para mostrar as reuniões da mais antiga para a mais recente.

Obrigado!

**Comment by ajdavidl** [comment]
Arquivo de decisões foi reordenado. [Commit 82fd476
](https://github.com/ajdavidl/corpus-atas-copom/commit/82fd476c976114dffa0e965507f96a0dd482025f)

**Comment by rprata** [comment]
Entendi, não me atentei para isso. Acho que se achar interessante daria para incluir um campo data da reunião futuramente nessa tabela, pq simplifica filtros e buscas em períodos.
